version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

init:
  - cmd: set BUILD_VERSION=%VERSION%.%APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_REPO_BRANCH%
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (set PROJECT_VERSION=%APPVEYOR_REPO_TAG_NAME%) ELSE (IF "%APPVEYOR_REPO_BRANCH%"=="master" (set PROJECT_VERSION=%BUILD_VERSION%) ELSE (IF "%APPVEYOR_REPO_BRANCH%"=="development" (set PROJECT_VERSION=%BUILD_VERSION%-dev) ELSE (set PROJECT_VERSION=%BUILD_VERSION%-pr)))
  - cmd: echo %PROJECT_VERSION%
  - cmd: echo %APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_BUILD_VERSION%
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

image: Visual Studio 2019

configuration: Release

platform: Any CPU

nuget:
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(PROJECT_VERSION)
  package_version: $(PROJECT_VERSION)
  assembly_version: $(PROJECT_VERSION)
  file_version: $(PROJECT_VERSION)
  informational_version: $(PROJECT_VERSION)

before_build:
- cmd: dotnet restore

build:
  verbosity: minimal
  publish_nuget: true
  include_nuget_references: true

after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: ls

artifacts:
  - path: bin
    name: bin

deploy:
- provider: NuGet
  api_key:
    secure: QszWgain24f3hNHfeUTlnCJDVi/njNTVUcdGJTQST0a0OFn6aC6YW1Np6cqzoTNY
  on:
    APPVEYOR_REPO_TAG: true